FROM ruby:2.2.2

# deps
RUN apt-get update -qq && apt-get install -y build-essential nodejs npm nodejs-legacy mysql-client vim

# Set up working directory
ENV APP_HOME=/codebeat-web
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

# Set up gems. This happens *before* the rest of the code is added in order to
# maximise the use of cache.
ADD Gemfile $APP_HOME/
ADD Gemfile.lock $APP_HOME/
RUN bundle install --jobs 20 --without development test

ADD . $APP_HOME
RUN npm install -g bower
RUN bower install --allow-root
RUN bundle exec rake assets:clobber
RUN bundle exec rake assets:precompile --trace
