FROM ruby:2.4.1-slim

# deps
RUN apt-get update -qq && \
    apt-get install -y build-essential vim git curl libpq-dev netcat
# node source
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get install -y nodejs

COPY Gemfile* ${APP_HOME}/
RUN bundle install

# install coffeelint
RUN npm install -g coffeelint jade
RUN gem install bundler

ENV RAILS_ENV=test
ENV RACK_ENV=test
ENV APP_HOME=/usr/src/app

# copy code
ADD . $APP_HOME
WORKDIR $APP_HOME
