default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  host: <%= ENV['DB_HOSTNAME'] %>
  port: <%= ENV['DB_PORT_NUMBER'] %>

development:
  <<: *default
  database: codequestmanager_development

test:
  <<: *default
  database: codequestmanager_test

production:
  <<: *default
  database: codequestmanager_production
  password: <%= ENV['DB_1_ENV_POSTGRES_PASSWORD'] %>
